{{ if .Values.dbJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-schema
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.appName }}-schema
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        envFrom:
          - secretRef:
              name: {{ .Values.appName }}
      restartPolicy: Never
  backoffLimit: 1
{{ end }}
