apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.appName }}
  dataFrom:
  - extract:
      key: {{ .Values.appName }}
